name: Maven CI

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags:
      - '!*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: testoutput-before
        run: |
          echo -- ls -al
          ls -al
          echo -- ls .mvn
          ls -R .mvn | true
          echo -- ls /home/runner/.m2/wrapper
          ls -R /home/runner/.m2/wrapper | true
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: testoutput-after
        run: |
          echo $M2_HOME
          echo -- settings.xml
          cat /home/runner/.m2/settings.xml
          echo -- ls -al
          ls -al
          echo -- ls .mvn
          ls -R .mvn | true
          echo -- ls /home/runner/.m2/wrapper
          ls -R /home/runner/.m2/wrapper | true
          echo -- mvnw -version
          ./mvnw -version | true
      - name: Build with Maven
        run: |
          ./mvnw --batch-mode --update-snapshots verify
          ./mvnw -version
      - uses: actions/upload-artifact@v2
        with:
          name: jar
          path: target/assertj-json-*.jar