name: Maven CI

on:
  push:
    branches:
      - '**'
    tags:
      - '!*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.MAVEN_GPG_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build with Maven
        run: |
          mvn --batch-mode --update-snapshots -Dgpg.passphrase=${{ secrets.MAVEN_GPG_KEY_PW }}  verify
          ls target
          cat target/*asc
      - uses: actions/upload-artifact@v2
        with:
          name: jar
          path: target/assertj-json-*.jar