name: Maven CI

on:
  push:
    branches:
      - '**'
    tags:
      - '!*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots verify
      - name: testoutput
        run: cat manifest.txt
      - uses: actions/upload-artifact@v2
        with:
          name: jar
          path: target/assertj-json-*.jar