name: Maven CI

on:
  push:
    branches:
      - '**'
    tags:
      - '!*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: testoutput-before
        run: |
          ls -R .mvn | true
          ls -R .m2/wrapper/ | true
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: testoutput-after
        run: |
          ls -R .mvn | true
          ls -R .m2/wrapper/ | true
          ./mvnw -version | true
          /usr/bin/tar --use-compress-program zstd -tvf /home/runner/work/_temp/4458ce2d-3355-4f24-93ef-c4730d8ca4ec/cache.tzst | true
      - name: Build with Maven
        run: |
          ./mvnw --batch-mode --update-snapshots verify
          ./mvnw -version
      - uses: actions/upload-artifact@v2
        with:
          name: jar
          path: target/assertj-json-*.jar