name: Maven CI

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags:
      - '!*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.m2/wrapper
            .mvn/wrapper/maven-wrapper.jar
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '.mvn/wrapper/maven-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: testoutput-after
        run: |
          echo -- ls -al
          ls -al
          echo -- ls -l .mvn/wrapper
          ls -l .mvn/wrapper | true
          echo -- ls -l ~/.m2/wrapper
          ls -l ~/.m2/wrapper | true
          echo -- mvnw -version
          ./mvnw -version | true
          echo -- mvnw -version
          ./mvnw -version | true
          echo -- ls -l ~/.m2/wrapper
          ls -l ~/.m2/wrapper | true
      - name: Build with Maven
        run: |
          ./mvnw --batch-mode --update-snapshots verify
          ./mvnw -version
      - uses: actions/upload-artifact@v2
        with:
          name: jar
          path: target/assertj-json-*.jar